
// Added to all id attributes generated by Javascript to avoid mix ups with other files.

const fileID = 'apostropheTest';

// Write the correct version of the sentences you wish to use as a test (including the apostrophe) into the textData object.
// The program will save the apostrophe's position and parse it out before displaying the sentences.

 const textData = [
    "Matilda is Louie's wife.",
    "Louie is Kate and Mary's father.",
    "Harry and Lucy are Sophie's cousins.",
    "Ken is Mary's husband.",
    "Katie and Tim are Sophie's parents."
 ]

